[workspace]

[package]
name = "borderless-gui-reactor"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
license = "MIT"
publish = false

[dependencies]
anyhow = "1.0.102"
borderless-core = { path = "../borderless-core" }
borderless-reacter = { path = "../borderless-reacter" }
borderless-win = { path = "../borderless-win" }
ractor = { version = "0.15.13", features = ["async-trait", "monitors"] }
tokio = { version = "1.52.3", features = ["rt-multi-thread", "macros", "sync", "time"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
windows-reactor = { git = "https://github.com/microsoft/windows-rs", branch = "master", package = "windows-reactor" }

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
unused_must_use = "deny"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
missing_const_for_fn = "allow"
redundant_pub_crate = "allow"
